language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
