language: node_js
node_js:
  - "14"
before_script:
  - npm install -g gulp
after_success:
  - cat ./coverage/lcov.info | cat - ./coverage.ios/lcov.info | cat - ./coverage.android/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
